### PR TITLE
Fix Targeting Unspawned Players

### LINKED ISSUE #550: bug: you can use target similar on self to kill unspawned players
this induces a game over desync
https://discord.com/channels/1032294536640200766/1070397640765874327/1218310717778694155

### PR DESCRIPTION
**Pull request by SoulMuncher**
closes #550 

Fixes a bug that allowed unspawned players to be targeted, which could cause a desync in the game over state. Adds further support for additional universal targeting catches by passing underworld as a parameter to the addTarget() function

QA Complete

### CODE REVIEW

File: src/cards/target_similar.ts [hunk 1]
```diff
@@ -50,6 +50,11 @@ export function targetSimilarEffect(numberOfTargets: number) {
         // @ts-ignore Find similar units by unitSourceId, find similar pickups by name
         .filter(t => {
           if (isUnit(target) && isUnit(t) && t.unitSourceId == target.unitSourceId) {
+            if (underworld.players.filter(p => !p.isSpawned).map(p => p.unit.id).includes(t.id)) {
+              // Do not allow targeting unspawned players
+              console.log("Filtered out unspawned player from target similar's potential targets");
+              return false;
+            }
```
Comment (jdoleary) [inline src/cards/target_similar.ts:57]: Isn't this redundant, now that addTarget omits unspawned players?

**Review by jdoleary — COMMENTED** [review]
Looks good, one comment

File: src/cards/target_similar.ts (hunk 1 above)
Comment (SoulMuncher) [reply src/cards/target_similar.ts:57]: Yes, it's redundant. I left it in this spot as well since unspawned players should probably *never* be targeted, and it'll serve as protection against future spells. Not absolutely necessary though, it comes at the cost of passing in underworld.

**Review by jdoleary — APPROVED** [review]
